server:
  port: 8080

spring:
  profiles:
    active: local

  application:
    name: Medad El Alia

  data:
    mongodb:
      host: localhost
      port: 27017
      uri: mongodb://localhost:27017/Medad_El_Alia
      authentication-database: Medad_El_Alia

springdoc:
  api-docs:
    path: /api-docs
    swagger-ui:
      path: /swagger-ui/index.html
      enable: false
