import { Book, Category, Author, Order, Review, Post, User } from '../src/types/index.js';

export const initialCategories: Category[] = [
  {
    id: 'cat-1',
    name: 'Literary Fiction',
    slug: 'literary-fiction',
    description: 'Profound narratives, character studies, and stylistically adventurous contemporary and classical fiction.',
    bookCount: 14,
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'cat-2',
    name: 'Philosophy & Essays',
    slug: 'philosophy-essays',
    description: 'Inquiries into ethics, perception, phenomenology, and essays on culture and existence.',
    bookCount: 11,
    image: 'https://images.unsplash.com/photo-1532012164546-f432f2e3edd4?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'cat-3',
    name: 'Architecture & Design',
    slug: 'architecture-design',
    description: 'Monographs on spatial design, typography, Bauhaus principles, and the built environment.',
    bookCount: 9,
    image: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'cat-4',
    name: 'Poetry & Solitude',
    slug: 'poetry-solitude',
    description: 'Bilingual editions, modernist verse, haiku translations, and meditative contemplations.',
    bookCount: 8,
    image: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'cat-5',
    name: 'History & Civilization',
    slug: 'history-civilization',
    description: 'Chronicles of ancient trade routes, archival histories, and lost literary traditions.',
    bookCount: 12,
    image: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'cat-6',
    name: 'Nature & Solitude',
    slug: 'nature-solitude',
    description: 'Environmental writing, biological wonders, mountaineering journals, and landscape theory.',
    bookCount: 7,
    image: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=600&q=80',
  },
];

export const initialAuthors: Author[] = [
  {
    id: 'aut-1',
    name: 'Elena Rostova',
    bio: 'Novelist and cultural critic based in Vienna. Recipient of the 2022 European Literature Prize, known for sparse syntax and atmospheric narratives.',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    nationality: 'Austria',
    booksCount: 5,
    notableWork: 'The Architecture of Solitude',
  },
  {
    id: 'aut-2',
    name: 'Dr. Tariq Al-Hassan',
    bio: 'Architectural historian and scholar of Andalusian urban design. Senior fellow at the Mediterranean Institute of Urbanity.',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    nationality: 'Spain / Morocco',
    booksCount: 4,
    notableWork: 'Monographs on Stone and Shadow',
  },
  {
    id: 'aut-3',
    name: 'Julian Vane',
    bio: 'Poet and master printer whose private press works are preserved in the Bodleian and Morgan libraries.',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    nationality: 'United Kingdom',
    booksCount: 6,
    notableWork: 'The Cartographer’s Dream',
  },
  {
    id: 'aut-4',
    name: 'Mei-Ling Zhao',
    bio: 'Comparative literature essayist and translator of classical Chinese aesthetics and modernist verse.',
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    nationality: 'Canada / Taiwan',
    booksCount: 3,
    notableWork: 'Essays on Form and Light',
  },
  {
    id: 'aut-5',
    name: 'Lars Lindqvist',
    bio: 'Philosopher examining Scandinavian phenomenological traditions, silence, and Arctic light psychology.',
    photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80',
    nationality: 'Sweden',
    booksCount: 4,
    notableWork: 'Meditations on Silence',
  },
];

export const initialBooks: Book[] = [
  {
    id: 'book-1',
    authorId: 'aut-1',
    authorName: 'Elena Rostova',
    bookTitle: 'The Architecture of Solitude',
    bookDescription: 'A meditative exploration of domestic spaces, quiet rooms, and the interior landscapes we inhabit when the noise of the world recedes. Written with razor-sharp prose and profound emotional stillness.',
    numberOfPages: 312,
    bookSize: '140 × 210 mm',
    coverType: 'Clothbound',
    paperType: 'Munken Premium Cream 115gsm',
    publicationYear: '2024-04-12',
    language: 'English',
    isbn: '978-0-14-312854-1',
    price: 34.00,
    discount: 15,
    stock: 28,
    coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    reviewCount: 42,
    categoryId: ['cat-1', 'cat-2'],
    categoryNames: ['Literary Fiction', 'Philosophy & Essays'],
    publisher: 'Inkora Editions',
    featured: true,
    bestseller: true,
    newArrival: false,
  },
  {
    id: 'book-2',
    authorId: 'aut-2',
    authorName: 'Dr. Tariq Al-Hassan',
    bookTitle: 'Invisible Cities & Echoes',
    bookDescription: 'Traces the architectural memories of Mediterranean ports from Alexandria to Venice. With 64 hand-drawn archival plans and historical essays on courtyards and wind towers.',
    numberOfPages: 448,
    bookSize: '170 × 240 mm',
    coverType: 'Hardcover',
    paperType: 'Fedrigoni Arcoprint 120gsm',
    publicationYear: '2024-02-18',
    language: 'English',
    isbn: '978-0-39-308945-8',
    price: 48.50,
    stock: 14,
    coverImage: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    reviewCount: 31,
    categoryId: ['cat-3', 'cat-5'],
    categoryNames: ['Architecture & Design', 'History & Civilization'],
    publisher: 'Alhambra Academic',
    featured: true,
    bestseller: false,
    newArrival: true,
  },
  {
    id: 'book-3',
    authorId: 'aut-3',
    authorName: 'Julian Vane',
    bookTitle: 'The Cartographer’s Dream',
    bookDescription: 'A sequence of 72 prose poems mapping mythical islands, abandoned lighthouses, and the celestial navigation of 17th-century astronomers. Typeset in revival Garamond with letterpress dust jacket.',
    numberOfPages: 184,
    bookSize: '130 × 195 mm',
    coverType: 'Paperback',
    paperType: 'Holmen Book Cream 90gsm',
    publicationYear: '2023-11-05',
    language: 'English',
    isbn: '978-1-59-463402-4',
    price: 22.00,
    discount: 10,
    stock: 45,
    coverImage: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=800&q=80',
    rating: 4.95,
    reviewCount: 56,
    categoryId: ['cat-4'],
    categoryNames: ['Poetry & Solitude'],
    publisher: 'Blackwood Press',
    featured: true,
    bestseller: true,
    newArrival: false,
  },
  {
    id: 'book-4',
    authorId: 'aut-4',
    authorName: 'Mei-Ling Zhao',
    bookTitle: 'Essays on Form and Light',
    bookDescription: 'How paper textures, morning shadows, and minimal brush strokes alter human contemplation. Zhao bridges Eastern calligraphy traditions with Scandinavian modernist furniture craft.',
    numberOfPages: 260,
    bookSize: '150 × 220 mm',
    coverType: 'Hardcover',
    paperType: 'Gmund Cotton Linen 110gsm',
    publicationYear: '2024-05-20',
    language: 'English',
    isbn: '978-0-81-299534-3',
    price: 36.00,
    stock: 19,
    coverImage: 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    reviewCount: 23,
    categoryId: ['cat-2', 'cat-3'],
    categoryNames: ['Philosophy & Essays', 'Architecture & Design'],
    publisher: 'Inkora Editions',
    featured: false,
    bestseller: false,
    newArrival: true,
  },
  {
    id: 'book-5',
    authorId: 'aut-5',
    authorName: 'Lars Lindqvist',
    bookTitle: 'Meditations on Silence',
    bookDescription: 'A philosophical monograph arguing for the conscious preservation of acoustic sanctuaries in modern hyper-connected cities. Rich with historical anecdotes and epistemological rigor.',
    numberOfPages: 290,
    bookSize: '140 × 210 mm',
    coverType: 'Clothbound',
    paperType: 'Munken Pure 100gsm',
    publicationYear: '2023-09-14',
    language: 'English',
    isbn: '978-0-52-555947-4',
    price: 32.50,
    discount: 20,
    stock: 9, // low stock alert for admin
    coverImage: 'https://images.unsplash.com/photo-1532012164546-f432f2e3edd4?auto=format&fit=crop&w=800&q=80',
    rating: 4.85,
    reviewCount: 38,
    categoryId: ['cat-2'],
    categoryNames: ['Philosophy & Essays'],
    publisher: 'Nordic University Press',
    featured: false,
    bestseller: true,
    newArrival: false,
  },
  {
    id: 'book-6',
    authorId: 'aut-1',
    authorName: 'Elena Rostova',
    bookTitle: 'The Winter Conservatory',
    bookDescription: 'In an isolated botanical glasshouse near the Baltic shore, three botanists catalog endangered alpine mosses while political turmoil transforms the mainland. A haunting, lyrical triumph.',
    numberOfPages: 368,
    bookSize: '145 × 215 mm',
    coverType: 'Hardcover',
    paperType: 'Enso Lux Cream 100gsm',
    publicationYear: '2023-01-10',
    language: 'English',
    isbn: '978-0-06-288834-1',
    price: 29.00,
    stock: 3, // very low stock
    coverImage: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    reviewCount: 65,
    categoryId: ['cat-1', 'cat-6'],
    categoryNames: ['Literary Fiction', 'Nature & Solitude'],
    publisher: 'Inkora Editions',
    featured: true,
    bestseller: true,
    newArrival: false,
  },
  {
    id: 'book-7',
    authorId: 'aut-2',
    authorName: 'Dr. Tariq Al-Hassan',
    bookTitle: 'The Book of Paper and Ink',
    bookDescription: 'A tactile history of bookbinding, botanical inks, and papermaking across medieval Samarkand, Fez, and Florence. Includes 16 colored photographic plates on heavy stock.',
    numberOfPages: 390,
    bookSize: '180 × 250 mm',
    coverType: 'Special Edition',
    paperType: 'Bespoke Rag Paper 130gsm',
    publicationYear: '2024-06-01',
    language: 'English',
    isbn: '978-0-30-747646-3',
    price: 58.00,
    stock: 22,
    coverImage: 'https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=800&q=80',
    rating: 5.0,
    reviewCount: 19,
    categoryId: ['cat-3', 'cat-5'],
    categoryNames: ['Architecture & Design', 'History & Civilization'],
    publisher: 'Inkora Editions',
    featured: true,
    bestseller: false,
    newArrival: true,
  },
  {
    id: 'book-8',
    authorId: 'aut-3',
    authorName: 'Julian Vane',
    bookTitle: 'The Labyrinth of Memory',
    bookDescription: 'A psychological tour-de-force navigating the archives of an antiquarian bookseller in post-war Prague. Where every marginalia note conceals a clandestine correspondence.',
    numberOfPages: 334,
    bookSize: '140 × 210 mm',
    coverType: 'Clothbound',
    paperType: 'Munken Print White 100gsm',
    publicationYear: '2023-08-22',
    language: 'English',
    isbn: '978-1-40-007927-8',
    price: 31.00,
    stock: 35,
    coverImage: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=800&q=80',
    rating: 4.75,
    reviewCount: 29,
    categoryId: ['cat-1', 'cat-5'],
    categoryNames: ['Literary Fiction', 'History & Civilization'],
    publisher: 'Blackwood Press',
    featured: false,
    bestseller: false,
    newArrival: false,
  },
];

export const initialReviews: Review[] = [
  {
    id: 'rev-1',
    bookId: 'book-1',
    bookTitle: 'The Architecture of Solitude',
    userId: 'usr-1',
    userName: 'Claire Montrose',
    rating: 5,
    comment: 'One of the most physically exquisite books on my shelf. The clothbound binding and paper stock reflect the exact reverence for stillness that Elena writes about.',
    date: '2024-05-18',
    status: 'APPROVED',
  },
  {
    id: 'rev-2',
    bookId: 'book-1',
    bookTitle: 'The Architecture of Solitude',
    userId: 'usr-2',
    userName: 'Arthur Pendelton',
    rating: 5,
    comment: 'Inkora’s edition is a collector’s dream. Elena’s chapter on twilight reading rooms brought tears to my eyes.',
    date: '2024-06-02',
    status: 'APPROVED',
  },
  {
    id: 'rev-3',
    bookId: 'book-2',
    bookTitle: 'Invisible Cities & Echoes',
    userId: 'usr-3',
    userName: 'Samira Belkacem',
    rating: 5,
    comment: 'Magnificent scholarship and breathtaking architectural sketches. Delivered within 48 hours in archival wrap.',
    date: '2024-06-12',
    status: 'APPROVED',
  },
  {
    id: 'rev-4',
    bookId: 'book-5',
    bookTitle: 'Meditations on Silence',
    userId: 'usr-4',
    userName: 'David Sterling',
    rating: 4,
    comment: 'Insightful philosophical critique. A must-read for any designer or writer suffering from sensory overload.',
    date: '2024-06-25',
    status: 'APPROVED',
  },
];

export const initialOrders: Order[] = [
  {
    id: 'ord-1001',
    orderNumber: 'INK-2024-8841',
    userId: 'usr-demo-user',
    customerName: 'Eleanor Vance',
    customerEmail: 'user@inkora.com',
    customerPhone: '+1 (555) 234-5678',
    items: [
      {
        bookId: 'book-1',
        bookTitle: 'The Architecture of Solitude',
        coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=400&q=80',
        authorName: 'Elena Rostova',
        price: 28.90,
        quantity: 1,
      },
      {
        bookId: 'book-3',
        bookTitle: 'The Cartographer’s Dream',
        coverImage: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=400&q=80',
        authorName: 'Julian Vane',
        price: 19.80,
        quantity: 1,
      },
    ],
    subtotal: 48.70,
    discountAmount: 5.00,
    shippingFee: 0,
    totalAmount: 43.70,
    status: 'DELIVERED',
    paymentMethod: 'ONLINE',
    paymentStatus: 'PAID',
    shippingDetails: {
      fullName: 'Eleanor Vance',
      email: 'user@inkora.com',
      phone: '+1 (555) 234-5678',
      address: '742 Evergreen Terrace, Apt 4B',
      city: 'Portland',
      postalCode: '97201',
      country: 'United States',
      notes: 'Please leave at the concierge desk.',
    },
    createdAt: '2024-05-24T14:32:00Z',
    updatedAt: '2024-05-28T10:15:00Z',
  },
  {
    id: 'ord-1002',
    orderNumber: 'INK-2024-9102',
    userId: 'usr-demo-user',
    customerName: 'Eleanor Vance',
    customerEmail: 'user@inkora.com',
    customerPhone: '+1 (555) 234-5678',
    items: [
      {
        bookId: 'book-7',
        bookTitle: 'The Book of Paper and Ink',
        coverImage: 'https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=400&q=80',
        authorName: 'Dr. Tariq Al-Hassan',
        price: 58.00,
        quantity: 1,
      },
    ],
    subtotal: 58.00,
    discountAmount: 0,
    shippingFee: 4.50,
    totalAmount: 62.50,
    status: 'SHIPPING',
    paymentMethod: 'ONLINE',
    paymentStatus: 'PAID',
    shippingDetails: {
      fullName: 'Eleanor Vance',
      email: 'user@inkora.com',
      phone: '+1 (555) 234-5678',
      address: '742 Evergreen Terrace, Apt 4B',
      city: 'Portland',
      postalCode: '97201',
      country: 'United States',
    },
    createdAt: '2024-06-03T09:12:00Z',
    updatedAt: '2024-06-04T16:20:00Z',
  },
  {
    id: 'ord-1003',
    orderNumber: 'INK-2024-9420',
    userId: 'usr-3',
    customerName: 'Gabriel Mercer',
    customerEmail: 'gabriel.mercer@oxon.ac.uk',
    customerPhone: '+44 20 7946 0912',
    items: [
      {
        bookId: 'book-2',
        bookTitle: 'Invisible Cities & Echoes',
        coverImage: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=400&q=80',
        authorName: 'Dr. Tariq Al-Hassan',
        price: 48.50,
        quantity: 2,
      },
      {
        bookId: 'book-5',
        bookTitle: 'Meditations on Silence',
        coverImage: 'https://images.unsplash.com/photo-1532012164546-f432f2e3edd4?auto=format&fit=crop&w=400&q=80',
        authorName: 'Lars Lindqvist',
        price: 26.00,
        quantity: 1,
      },
    ],
    subtotal: 123.00,
    discountAmount: 12.00,
    shippingFee: 0,
    totalAmount: 111.00,
    status: 'PROCESSING',
    paymentMethod: 'ONLINE',
    paymentStatus: 'PAID',
    shippingDetails: {
      fullName: 'Gabriel Mercer',
      email: 'gabriel.mercer@oxon.ac.uk',
      phone: '+44 20 7946 0912',
      address: '14 St Giles Quarter',
      city: 'Oxford',
      postalCode: 'OX1 3JP',
      country: 'United Kingdom',
    },
    createdAt: '2024-06-05T11:45:00Z',
    updatedAt: '2024-06-05T12:00:00Z',
  },
  {
    id: 'ord-1004',
    orderNumber: 'INK-2024-9588',
    userId: 'usr-4',
    customerName: 'Sora Takahashi',
    customerEmail: 'sora.t@kyotocraft.jp',
    customerPhone: '+81 75 123 4567',
    items: [
      {
        bookId: 'book-4',
        bookTitle: 'Essays on Form and Light',
        coverImage: 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?auto=format&fit=crop&w=400&q=80',
        authorName: 'Mei-Ling Zhao',
        price: 36.00,
        quantity: 1,
      },
    ],
    subtotal: 36.00,
    discountAmount: 0,
    shippingFee: 12.00,
    totalAmount: 48.00,
    status: 'CONFIRMED',
    paymentMethod: 'CASH',
    paymentStatus: 'PENDING',
    shippingDetails: {
      fullName: 'Sora Takahashi',
      email: 'sora.t@kyotocraft.jp',
      phone: '+81 75 123 4567',
      address: 'Higashiyama-ku, Gojo-dori 88',
      city: 'Kyoto',
      postalCode: '605-0801',
      country: 'Japan',
    },
    createdAt: '2024-06-06T08:14:00Z',
    updatedAt: '2024-06-06T08:14:00Z',
  },
];

export const initialPosts: Post[] = [
  {
    id: 'post-1',
    title: 'The Sensual Geometry of the Private Library',
    content: 'Why does the proportion of a bookshelf alter the tempo of our thinking? In this essay, we examine the monastic reading rooms of St. Gall and the domestic bookshelves designed by Charlotte Perriand.',
    authorName: 'Julian Vane',
    authorRole: 'Senior Literary Editor',
    coverImage: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=800&q=80',
    publishedAt: '2024-05-30',
    likesCount: 142,
    commentsCount: 18,
    tags: ['Architecture', 'Essays', 'Reading Culture'],
  },
  {
    id: 'post-2',
    title: 'Munken Cream vs. Rag Paper: The Tactile Science of Inks',
    content: 'A deep dive into paper weights, opacity, cotton fiber sizing, and why offset lithography on unbleached wood-free stock creates an indelible connection between reader and author.',
    authorName: 'Dr. Tariq Al-Hassan',
    authorRole: 'Master of Typography',
    coverImage: 'https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=800&q=80',
    publishedAt: '2024-05-15',
    likesCount: 98,
    commentsCount: 12,
    tags: ['Typography', 'Craft', 'Print Culture'],
  },
];

export const demoUsers: User[] = [
  {
    id: 'usr-admin-1',
    username: 'admin',
    email: 'admin@inkora.com',
    role: 'ADMIN',
    address: '10 Old Bailey, London EC4M 7NG',
    phoneNumber: '+44 20 7946 0192',
    createdAt: '2023-01-01T00:00:00Z',
  },
  {
    id: 'usr-demo-user',
    username: 'eleanor_vance',
    email: 'user@inkora.com',
    role: 'USER',
    address: '742 Evergreen Terrace, Apt 4B, Portland, OR 97201',
    phoneNumber: '+1 (555) 234-5678',
    createdAt: '2023-08-14T00:00:00Z',
  },
  {
    id: 'usr-agent-1',
    username: 'agent_marcus',
    email: 'agent@inkora.com',
    role: 'AGENT',
    address: '22 Baker St, London NW1 6XE',
    phoneNumber: '+44 20 7946 0884',
    createdAt: '2023-09-01T00:00:00Z',
  },
];
