server:
  port: 8080

spring:
  application:
    name: Inkora


  mail:
    host: smtp.gmail.com
    port: 587
    username: kerolosshoukry3@gmail.com
    password: ksoc lzyj hljt vwhe
    from: kerolos
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/Inkora

  logging:
    level:
      org.springframework.security: TRACE
      org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "health,mappings"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    enabled: true

jwt:
  secret: yourBase64EncodedKeyHereksjbfkjahbsd
